WITH END_TIME AS (
SELECT WAREHOUSE_NAME,TIMESTAMP,event_name ,row_number() over (PARTITION BY WAREHOUSE_NAME ORDER BY TIMESTAMP ASC) RANK
from snowflake.account_usage.warehouse_events_history where event_name in ('SUSPEND_WAREHOUSE','RESUME_WAREHOUSE')
and event_state='COMPLETED' order by timestamp asc
),
START_TIME AS(
SELECT WAREHOUSE_NAME,TIMESTAMP,EVENT_NAME, RANK  FROM(
SELECT WAREHOUSE_NAME,TIMESTAMP,event_name ,row_number() over (PARTITION BY WAREHOUSE_NAME ORDER BY TIMESTAMP ASC) RANK
from snowflake.account_usage.warehouse_events_history where event_name in ('SUSPEND_WAREHOUSE','RESUME_WAREHOUSE')
and event_state='COMPLETED' order by timestamp asc
)
    )
SELECT TO_DATE(START_TIME) START_TIME,WAREHOUSE_NAME, COUNT(MINUTES) as FREQUENCY FROM (
SELECT WAREHOUSE_NAME,START_TIME,END_TIME, MINUTES FROM (
SELECT WAREHOUSE_NAME,START_TIME,END_TIME ,MINUTES ,ROW_NUMBER() OVER (PARTITION BY WAREHOUSE_NAME ORDER BY START_TIME ASC) RANK  FROM (
SELECT A.WAREHOUSE_NAME,A.TIMESTAMP START_TIME,B.TIMESTAMP END_TIME, datediff(minute,A.TIMESTAMP,B.TIMESTAMP) MINUTES
FROM
START_TIME A 
INNER JOIN
END_TIME B
ON A.RANK+1=B.RANK
    
)
) WHERE MOD(RANK,2)=0) 
where WAREHOUSE_NAME=:my_warehouse
GROUP BY TO_DATE(START_TIME)  , WAREHOUSE_NAME
ORDER BY START_TIME DESC
