SELECT * FROM sNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.pART WHERE P_PARTKEY ='120922803';


SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER WHERE C_CUSTKEY='50900001';


CREATE TABLE DEMO_DB.PUBLIC.PART_SOS
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PART;


CREATE TABLE DEMO_DB.PUBLIC.CUSTOMER_SOS
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER;

ALTER TABLE DEMO_DB.PUBLIC.PART_SOS ADD SEARCH OPTIMIZATION ON EQUALITY(P_PARTKEY);

ALTER TABLE DEMO_DB.PUBLIC.CUSTOMER_SOS ADD SEARCH OPTIMIZATION ON EQUALITY(C_CUSTKEY);

SELECT * FROM DEMO_DB.PUBLIC.PART_SOS WHERE P_PARTKEY ='120922803';
SELECT * FROM DEMO_DB.PUBLIC.CUSTOMER_SOS WHERE C_CUSTKEY='50900001';