SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.pARTSUPP limit 100;

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.pARTSUPP WHERE PS_AVAILQTY='1495'

CREATE TABLE DEMO_DB.PUBLIC.PARTSUPP_SOS
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.PARTSUPP;

ALTER TABLE DEMO_DB.PUBLIC.PARTSUPP_SOS ADD SEARCH OPTIMIZATION ON EQUALITY(PS_AVAILQTY);

-- almost no difference in query response time (table not big enough to see a difference)
SELECT * FROM DEMO_DB.PUBLIC.PARTSUPP_SOS  WHERE PS_AVAILQTY='1495';
SHOW TABLES

-- almost no difference in query response time (table not big enough to see a difference)
SELECT * FROM DEMO_DB.PUBLIC.PARTSUPP  WHERE PS_AVAILQTY='1495';


ALTER TABLE SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.pARTSUPP ADD SEARCH OPTIMIZATION ON EQUALITY(PS_AVAILQTY);
