SELECT WAREHOUSE_NAME,ROUND(((SUM(TOTAL_ELAPSED_TIME)/1000)/60)/60,2) Hours_utilized FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE WAREHOUSE_NAME=:my_warehouse and TO_DATE(START_TIME)=:daterange
GROUP BY WAREHOUSE_NAME;
